// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWn41yfy4LNG1hoBHVJlPWpA29F6b_7ww',
    appId: '1:994018420997:web:3cfb8ba107a564fa0baf6c',
    messagingSenderId: '994018420997',
    projectId: 'appagendamiento-ddbd0',
    authDomain: 'appagendamiento-ddbd0.firebaseapp.com',
    storageBucket: 'appagendamiento-ddbd0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE3pl60HtLpFgBnq_FTfZzviGmndKwPmI',
    appId: '1:994018420997:android:63f43542e9e6c2640baf6c',
    messagingSenderId: '994018420997',
    projectId: 'appagendamiento-ddbd0',
    storageBucket: 'appagendamiento-ddbd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADPp01BNiR3pLOqDtNIXtffvQuvAtXG_A',
    appId: '1:994018420997:ios:f8df533ad03cd2530baf6c',
    messagingSenderId: '994018420997',
    projectId: 'appagendamiento-ddbd0',
    storageBucket: 'appagendamiento-ddbd0.firebasestorage.app',
    iosBundleId: 'com.example.appAgendamiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADPp01BNiR3pLOqDtNIXtffvQuvAtXG_A',
    appId: '1:994018420997:ios:f8df533ad03cd2530baf6c',
    messagingSenderId: '994018420997',
    projectId: 'appagendamiento-ddbd0',
    storageBucket: 'appagendamiento-ddbd0.firebasestorage.app',
    iosBundleId: 'com.example.appAgendamiento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWn41yfy4LNG1hoBHVJlPWpA29F6b_7ww',
    appId: '1:994018420997:web:681d96e93b0c03490baf6c',
    messagingSenderId: '994018420997',
    projectId: 'appagendamiento-ddbd0',
    authDomain: 'appagendamiento-ddbd0.firebaseapp.com',
    storageBucket: 'appagendamiento-ddbd0.firebasestorage.app',
  );
}
