# Apuntar a una versión específica de JDK para evitar incompatibilidades
org.gradle.java.home=/usr/local/Cellar/openjdk@17/17.0.16/libexec/openjdk.jdk/Contents/Home

# Habilitar AndroidX y Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Aumentar la memoria para el demonio de Gradle para evitar errores de Metaspace
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
